namespace VirtueSky.Inspector
{
    public enum CustomColor
    {
        Aqua,
        Beige,
        Black,
        Blue,
        BlueVariant,
        DarkBlue,
        Bright,
        Brown,
        Cyan,
        DarkGray,
        Fuchsia,
        Gray,
        Green,
        Indigo,
        LightGray,
        Lime,
        Navy,
        Olive,
        DarkOlive,
        Orange,
        OrangeVariant,
        Pink,
        Red,
        LightRed,
        RedVariant,
        DarkRed,
        Tan,
        Teal,
        Violet,
        White,
        Yellow
    }
}